### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Delux2** [FrazzIe/old-core-framework#2]
The login script seems to not work...I have tried so many things but still it gives me error messages.

Pic: https://imgur.com/a/8xPQb8V

pic2: https://imgur.com/a/Mqw608N

Can u help me and tell me what might be wrong?

**Comment by ElusionPDX** [comment]
Your missing a folder on your main C drive called "data"  🍡

**Comment by CallowayIsWeird** [comment]
Same problem as @Delux2. Need some guidance here.

**Comment by ElusionPDX** [comment]
fcore is broken. You would need to repair it and build it more.
No support for it, he says it on the fivem forum post 
"The github files aren’t functional, its not plug and play and even if you get this to work you just shouldn’t use it without changing a lot (especially the stupid way i saved and loaded data)"
https://forum.fivem.net/t/release-source-code-from-a-framework-i-made-back-in-august-2017/107257"

Add me on discord if you want to talk about making it work  Beerasaurus - Rex#9371

**Comment by Tyler-Moose** [comment]
If anybody can shine some light Tyler Moose#6227 add me
